import * as THREE from 'three';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { getAsset, saveAsset } from '../shared/asset-store.js';

const $=id=>document.getElementById(id),assetId=new URLSearchParams(location.search).get('asset');
let asset,root,balls=[],selected=-1,assignments={},highlighted=[],slotLookup=new Map(),controls,allowPick=false,pointerStart=null;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xf2f5f8);
const camera=new THREE.PerspectiveCamera(35,1,.01,100),renderer=new THREE.WebGLRenderer({canvas:$('partsCanvas'),antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.75;scene.add(new THREE.HemisphereLight(0xdbe4ef,0x4e5865,.9));const key=new THREE.DirectionalLight(0xfff4e6,1.4);key.position.set(4,7,5);scene.add(key);
function fit(){if(!root)return;root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(root),sphere=box.getBoundingSphere(new THREE.Sphere()),distance=sphere.radius/Math.sin(THREE.MathUtils.degToRad(camera.fov/2))*1.06;camera.position.copy(sphere.center).add(new THREE.Vector3(1,.55,1).normalize().multiplyScalar(distance));controls.target.copy(sphere.center);controls.update();}
function clearHighlight(){for(const item of highlighted){item.mesh.material=item.original;item.clones.forEach(material=>material.dispose());}highlighted=[];}
function highlight(ball){clearHighlight();const byMesh=new Map();for(const slot of ball.slots){let item=byMesh.get(slot.mesh);if(!item){item={mesh:slot.mesh,original:slot.mesh.material,materials:Array.isArray(slot.mesh.material)?slot.mesh.material.slice():[slot.mesh.material],clones:[]};byMesh.set(slot.mesh,item);}const clone=item.materials[slot.slot].clone();if(clone.emissive){clone.emissive.set(0x4c9aff);clone.emissiveIntensity=.8;}item.materials[slot.slot]=clone;item.clones.push(clone);}for(const item of byMesh.values()){item.mesh.material=Array.isArray(item.original)?item.materials:item.materials[0];highlighted.push(item);}}
function select(index){selected=index;const ball=balls[index];if(!ball)return;highlight(ball);$('partsEmpty').hidden=true;$('partsEditor').hidden=false;$('partName').textContent=ball.name;$('partUsage').textContent=`应用于 ${ball.slots.length} 个材质槽`;for(const input of document.querySelectorAll('.part-check input'))input.checked=!!assignments[ball.key]?.includes(input.value);document.querySelectorAll('.parts-list button').forEach(button=>button.classList.toggle('active',Number(button.dataset.index)===index));}
function enumerateMaterials(){const byMaterial=new Map();slotLookup=new Map();root.traverse(mesh=>{if(!mesh.isMesh)return;const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];materials.forEach((material,slot)=>{if(!material)return;let ball=byMaterial.get(material);if(!ball){const key=String(byMaterial.size);ball={key,name:material.name||`材质球 ${Number(key)+1}`,material,slots:[]};byMaterial.set(material,ball);balls.push(ball);}ball.slots.push({mesh,slot});slotLookup.set(mesh.uuid+':'+slot,ball);});});$('partsCount').textContent=`${balls.length} 个材质球 · 可配置分类`;const list=$('partsList');list.replaceChildren();balls.forEach((ball,index)=>{const button=document.createElement('button');button.dataset.index=index;const swatch=document.createElement('span');swatch.className='part-swatch';swatch.style.setProperty('--swatch','#'+(ball.material.color?.getHexString?.()||'ffffff'));const name=document.createElement('span');name.textContent=ball.name;const count=document.createElement('small');count.textContent=`${ball.slots.length} 槽`;button.append(swatch,name,count);button.onclick=()=>select(index);list.append(button);});}
function toggle(type,enabled){if(selected<0)return;const key=balls[selected].key,current=new Set(assignments[key]||[]);if(enabled)current.add(type);else current.delete(type);if(current.size)assignments[key]=[...current];else delete assignments[key];}
function resize(){const rect=$('partsCanvas').getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/Math.max(1,rect.height);camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('partsCanvas'));
function pick(event){const rect=$('partsCanvas').getBoundingClientRect(),pointer=new THREE.Vector2((event.clientX-rect.left)/rect.width*2-1,1-(event.clientY-rect.top)/rect.height*2),ray=new THREE.Raycaster();ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(root?root.children:[],true)[0];if(!hit)return;const slot=Array.isArray(hit.object.material)?(hit.face?.materialIndex??0):0,ball=slotLookup.get(hit.object.uuid+':'+slot);if(ball)select(balls.indexOf(ball));}
document.querySelectorAll('.part-check input').forEach(input=>input.onchange=()=>toggle(input.value,input.checked));$('partsCanvas').addEventListener('pointerdown',event=>{pointerStart={x:event.clientX,y:event.clientY};allowPick=false;});$('partsCanvas').addEventListener('pointerup',event=>{allowPick=!!pointerStart&&Math.hypot(event.clientX-pointerStart.x,event.clientY-pointerStart.y)<5;pointerStart=null;});$('partsCanvas').addEventListener('click',event=>{if(allowPick)pick(event);allowPick=false;});
$('saveParts').onclick=async()=>{if(!asset)return;const button=$('saveParts');button.disabled=true;try{await saveAsset({...asset,partAssignments:assignments});$('partsStatus').textContent='已保存材质球分类';}catch(error){$('partsStatus').textContent='保存失败：'+error.message;}finally{button.disabled=false;}};
async function init(){try{asset=await getAsset(assetId);if(!asset||asset.kind!=='model')throw new Error('模型资产不存在');$('partsTitle').textContent=asset.name;assignments=asset.partAssignments&&typeof asset.partAssignments==='object'?JSON.parse(JSON.stringify(asset.partAssignments)):{};const resources=new Map((asset.resources||[]).map(file=>[file.name.split(/[\\/]/).pop().toLowerCase(),file])),manager=new THREE.LoadingManager();manager.setURLModifier(url=>{const file=resources.get(decodeURIComponent(url.replace(/\\/g,'/').split('/').pop()).toLowerCase());return file?URL.createObjectURL(file):url;});const modelUrl=URL.createObjectURL(asset.file);root=await new FBXLoader(manager).loadAsync(modelUrl);URL.revokeObjectURL(modelUrl);root.traverse(mesh=>{if(mesh.isMesh){mesh.castShadow=true;mesh.receiveShadow=true;const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];materials.forEach(material=>{if(material?.color)material.color.set(0x9ca3aa);});}});scene.add(root);controls=new OrbitControls(camera,$('partsCanvas'));controls.enableDamping=true;controls.dampingFactor=.075;controls.autoRotate=true;controls.autoRotateSpeed=.35;controls.maxPolarAngle=Math.PI*.49;controls.screenSpacePanning=true;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.PAN,RIGHT:THREE.MOUSE.PAN};const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),scale=5.25/Math.max(...size.toArray()),center=box.getCenter(new THREE.Vector3());root.scale.setScalar(scale);root.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);enumerateMaterials();fit();resize();$('partsLoading').hidden=true;renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});}catch(error){$('partsLoading').textContent='载入失败：'+error.message;}}
init();
