import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createAssetCloud } from '../shared/asset-cloud.js';
import { retainProjectSources } from '../shared/project-manifest.js';

const alice = '11111111-1111-1111-1111-111111111111', bob = '22222222-2222-2222-2222-222222222222';
function fixture() {
  const rows = new Map(), stars = new Map(), blobs = new Map(), downloads = [], fields = [];
  let userId = alice, uploads = 0, revision = 0;
  const client = {
    from(table) {
      const filters = {}; let selection = '*', operation = 'select', data, start = 0, end = 199;
      const collection = table === 'spenic_assets' ? rows : stars;
      const builder = {
        select(value = '*') { selection = value; fields.push({ table, value }); return this; },
        eq(key, value) { filters[key] = value; return this; }, order() { return this; },
        range(a, b) { start = a; end = b; return this; },
        delete() { operation = 'delete'; return this; }, upsert(row) { data = row; operation = 'upsert'; return this; },
        async maybeSingle() { return { data: [...collection.values()].find(row => Object.entries(filters).every(([key, value]) => row[key] === value)) || null }; },
        then(resolve, reject) {
          return Promise.resolve().then(() => {
            if (operation === 'upsert') { collection.set(data.owner_id + ':' + data.asset_id, data); return { data: null }; }
            const values = [...collection.values()].filter(row => Object.entries(filters).every(([key, value]) => row[key] === value));
            if (operation === 'delete') for (const row of values) collection.delete(row.id || row.owner_id + ':' + row.asset_id);
            return { data: values.slice(start, end + 1).map(row => selection === '*' ? row : Object.fromEntries(selection.split(',').map(key => [key, row[key]]))) };
          }).then(resolve, reject);
        },
      }; return builder;
    },
    async rpc(name, args) {
      assert.equal(name, 'spenic_save_asset');
      const row = args.asset_data, old = rows.get(row.id);
      if (old && old.owner_id !== userId) return { error: { code: '42501' } };
      if (old && old.updated_at !== args.expected_revision) return { error: { code: '40001' } };
      const next = { ...row, owner_id: userId, created_at: old?.created_at || '2026-10-09T00:00:00Z', updated_at: new Date(1800000000000 + revision++).toISOString() };
      rows.set(row.id, next); return { data: next };
    },
    storage: { from() { return { async createSignedUrls(paths) { return { data: paths.map(path => ({ path, signedUrl: 'https://assets.test/' + path })) }; } }; } },
  };
  const resources = {
    async upload(file) {
      const hash = [...new Uint8Array(await crypto.subtle.digest('SHA-256', await file.arrayBuffer()))].map(x => x.toString(16).padStart(2, '0')).join('');
      const path = userId + '/' + hash;
      if (!blobs.has(path)) { uploads++; blobs.set(path, file); }
      return { kind: 'cloud', hash, path, size: file.size, name: file.name || 'preview.png', type: file.type };
    },
    async download(ref) { downloads.push(ref.path); return blobs.get(ref.path); },
  };
  return { cloud: createAssetCloud(async () => ({ client, userId }), resources), rows, stars, downloads, fields, blobs,
    setUser(id) { userId = id; }, get uploads() { return uploads; } };
}
const material = () => ({ kind: 'material', name: '面料', materialType: 'fabric', category: '面布',
  physical: { widthCm: 12, heightCm: 8 }, surface: { color: '#ffffff', roughness: .6 },
  maps: { map: new File(['original-color'], 'original.png', { type: 'image/png' }) }, preview: new Blob(['preview'], { type: 'image/png' }) });

test('public asset lists load metadata and thumbnails; source maps and runtime maps hydrate only on demand', async () => {
  const f = fixture(), saved = await f.cloud.save(material());
  // Distinct prepared data represents an image generated by the browser resizer.
  const runtime = new File(['runtime'], 'runtime.png', { type: 'image/png' });
  const hash = 'a'.repeat(64), path = alice + '/' + hash; f.blobs.set(path, runtime);
  f.rows.get(saved.id).manifest.files['runtime/map'] = { kind: 'cloud', path, hash, size: runtime.size, name: runtime.name, type: runtime.type };
  f.setUser(bob);
  const [card] = await f.cloud.list();
  assert.equal(card.name, '面料'); assert.equal(card.ownerId, alice);
  assert.equal(card.maps, undefined); assert.equal(card.assetManifest, undefined); assert.equal(f.downloads.length, 0);
  assert.equal(f.fields.filter(x => x.table === 'spenic_assets' && x.value.includes('manifest')).length, 0);
  const asset = await f.cloud.get(saved.id, { runtime: true });
  assert.equal(await asset.maps.map.text(), 'runtime'); assert.equal(f.downloads.length, 1);
  assert.equal(asset.runtimeOnly, true); assert.equal(asset.projectRefs.map.prepared, true);
  await f.cloud.get(saved.id, { runtime: true }); assert.equal(f.downloads.length, 1);
  const source = await f.cloud.source(asset.sourcePackage); assert.equal(await source.maps.map.text(), 'original-color');
  assert.equal(asset.physical.widthCm, 12);
});

test('metadata updates do not download textures; stale writers and nonowners cannot change originals', async () => {
  const f = fixture(), saved = await f.cloud.save(material());
  await f.cloud.update(saved.id, { name: '修改名称', supplier: '供应商' });
  assert.equal(f.downloads.length, 0); assert.equal(f.rows.get(saved.id).metadata.supplier, '供应商');
  await assert.rejects(f.cloud.save({ ...saved, name: 'stale' }), /其他页面更新/);
  f.setUser(bob);
  await assert.rejects(f.cloud.update(saved.id, { name: 'overwrite' }), /上传者/);
  await assert.rejects(f.cloud.remove(saved.id), /上传者/);
  assert.equal(f.rows.get(saved.id).name, '修改名称');
});

test('saving another users runtime asset forks without reuploading; favorites belong to each account', async () => {
  const f = fixture(), saved = await f.cloud.save(material()), uploads = f.uploads;
  f.setUser(bob); const asset = await f.cloud.get(saved.id, { runtime: true });
  const copy = await f.cloud.save({ ...asset, name: '副本' });
  assert.notEqual(copy.id, saved.id); assert.equal(copy.ownerId, bob); assert.equal(f.uploads, uploads);
  await f.cloud.favorite(saved.id, true); assert.equal((await f.cloud.favorites()).has(saved.id), true);
  f.setUser(alice); assert.equal((await f.cloud.favorites()).size, 0);
  f.setUser(bob); await f.cloud.favorite(saved.id, false); assert.equal((await f.cloud.favorites()).size, 0);
  const config = { files: { 'textures/map': asset.projectRefs.map } };
  retainProjectSources(config);
  assert.ok(Object.values(config.files).some(ref => ref.path === asset.sourcePackage.files.map.path));
});

test('cloud model and image assets restore original files and companion resources', async () => {
  const f = fixture();
  const model = await f.cloud.save({ kind: 'model', name: 'model.glb', file: new File(['glb'], 'model.glb'), resources: [new File(['png'], 'normal.png')] });
  const restored = await f.cloud.get(model.id);
  assert.equal(restored.file.name, 'model.glb'); assert.equal(restored.resources[0].name, 'normal.png');
  const texture = await f.cloud.save({ kind: 'texture', name: 'image.png', file: new File(['image'], 'image.png', { type: 'image/png' }) });
  assert.equal((await f.cloud.get(texture.id, { runtime: true })).runtimeFile.name, 'image.png');
});
