const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

(async () => {
  const root = path.resolve(__dirname, '..');
  const html = (await fs.readFile(path.join(root, 'design.html'), 'utf8')).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '');
  const fixtures = [
    { id: 'outer', kind: 'folder', library: 'fabric', name: '面料文件夹', updatedAt: 3 },
    { id: 'inner', kind: 'folder', library: 'fabric', parentId: 'outer', name: '子文件夹', updatedAt: 2 },
    { id: 'nested', kind: 'material', parentId: 'inner', name: '子目录面料', category: '面布', updatedAt: 1 },
    { id: 'root-material', kind: 'material', name: '根目录面料', updatedAt: 1 },
    { id: 'patterns', kind: 'folder', library: 'pattern', name: '图案文件夹', updatedAt: 1 },
    { id: 'pattern', kind: 'material', materialType: 'pattern', parentId: 'patterns', name: '子目录图案', updatedAt: 1 },
    ...Array.from({ length: 30 }, (_, index) => ({ id: 'extra-' + index, kind: 'material', parentId: 'inner', name: '面料 ' + index, category: ['面布', '边布', '包边条', '其他'][index % 4], surface: { color: ['#884ab1', '#edd086', '#235888', '#65a583'][index % 4] }, updatedAt: 1 })),
  ];
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.route('http://picker.test/**', async route => {
      const name = new URL(route.request().url()).pathname.slice(1);
      if (!name || name === 'design.html') return route.fulfill({ contentType: 'text/html', body: html });
      if (name === 'shared/asset-store.js') return route.fulfill({ contentType: 'text/javascript', body: `export async function listAssets({onProgress}={}){const items=${JSON.stringify(fixtures)};onProgress?.(items);return items;}` });
      if (name === 'shared/material-placement.js') return route.fulfill({ contentType: 'text/javascript', body: "export const materialType = asset => asset.materialType === 'pattern' ? 'pattern' : 'fabric';" });
      try {
        await route.fulfill({ contentType: name.endsWith('.css') ? 'text/css' : name.endsWith('.js') ? 'text/javascript' : 'application/octet-stream', body: await fs.readFile(path.join(root, name)) });
      } catch { await route.fulfill({ status: 404, body: '' }); }
    });
    await page.goto('http://picker.test/design.html');
    await page.evaluate(async () => {
      const { createDesignWorkspace } = await import('./design-workspace.js');
      window.addedAssets = []; window.addAttempts = []; window.pickerNotifications = [];
      window.pickerWorkspace = createDesignWorkspace({ cancelPlacement() {}, undo() {}, showScene() {}, add: async asset => {
        window.addAttempts.push(asset.id);
        if (window.pausePickerAdd) await new Promise(resolve => { window.resumePickerAdd = resolve; });
        if (window.failPickerAsset === asset.id) throw new Error('测试添加失败');
        window.addedAssets.push(asset.id);
      }, notify(message) { window.pickerNotifications.push(message); } });
      document.getElementById('materialDock').classList.remove('opening-hidden');
    });
    const open = () => page.evaluate(() => document.getElementById('addDockAsset').click());
    const card = id => page.locator(`[data-asset-id="${id}"]`);
    const dialogBounds = () => page.locator('#assetPicker').boundingBox();
    await open();
    await card('outer').waitFor();
    assert.equal(await page.locator('#confirmAssetPicker').isDisabled(), true);
    assert.equal(await page.locator('#pickerBack').isDisabled(), true);
    assert.equal(await page.locator('.picker-card').count(), 2);
    await card('outer').click();
    assert.equal(await page.locator('#pickerBack').isEnabled(), true);
    await card('inner').click();
    await page.locator('#pickerSearch').fill('不存在');
    assert.equal(await page.locator('.picker-card').count(), 0);
    await page.locator('#pickerBack').click();
    assert.equal(await page.locator('#pickerSearch').inputValue(), '');
    assert.equal(await card('inner').count(), 1);
    await page.locator('#pickerBack').click();
    assert.equal(await page.locator('#pickerBack').isDisabled(), true);
    assert.equal(await card('outer').count(), 1);
    for (const width of [1440, 760, 390]) {
      await page.setViewportSize({ width, height: 1000 });
      const initialBounds = await dialogBounds();
      await page.locator('#pickerSearch').fill('不存在');
      assert.equal(await page.locator('.picker-card').count(), 0);
      assert.deepEqual(await dialogBounds(), initialBounds, 'Empty results keep the dialog size and position');
      await page.locator('#pickerSearch').fill('根目录');
      assert.equal(await page.locator('.picker-card').count(), 1);
      assert.deepEqual(await dialogBounds(), initialBounds, 'One card keeps the dialog size and position');
      await page.locator('#pickerSearch').fill('');
      await card('outer').click(); await card('inner').click();
      assert.deepEqual(await dialogBounds(), initialBounds, 'Many cards keep the dialog size and position');
      const headerBounds = await page.locator('#assetPicker header').boundingBox();
      await page.mouse.move(headerBounds.x + 5, headerBounds.y + 5);
      await page.waitForFunction(() => getComputedStyle(document.querySelector('.picker-card')).transform === 'none');
      const firstBounds = await page.locator('.picker-card').first().boundingBox();
      assert.ok(Math.abs(firstBounds.y - (headerBounds.y + headerBounds.height + 13)) <= 1, 'Cards start 13px below the header');
      const trackBounds = await page.locator('#pickerScrollbar').boundingBox();
      assert.equal(trackBounds.width, 10);
      assert.ok(Math.abs(trackBounds.x + trackBounds.width - (initialBounds.x + initialBounds.width - 1)) <= 1, 'Scrollbar sits at the dialog right edge');
      assert.ok(Math.abs(trackBounds.y - (headerBounds.y + headerBounds.height)) <= 1, 'Scrollbar starts directly below the header');
      assert.ok(Math.abs(trackBounds.y + trackBounds.height - (initialBounds.y + initialBounds.height - 1)) <= 1, 'Scrollbar ends at the dialog bottom');
      const closeBounds = await page.locator('#closeAssetPicker').boundingBox();
      await page.waitForFunction(() => getComputedStyle(document.getElementById('confirmAssetPicker')).width === '34px');
      const confirmBounds = await page.locator('#confirmAssetPicker').boundingBox();
      assert.equal(confirmBounds.x, closeBounds.x, 'Confirm is vertically aligned with Close');
      assert.equal(confirmBounds.width, closeBounds.width);
      assert.equal(confirmBounds.height, closeBounds.height);
      assert.ok(Math.abs((closeBounds.y - initialBounds.y) - (initialBounds.y + initialBounds.height - confirmBounds.y - confirmBounds.height)) <= 1, 'Confirm mirrors Close at the bottom');
      const scrollbarStyles = await page.locator('.picker-scrollbar-thumb').evaluate(element => { const s = getComputedStyle(element); return { color: s.backgroundColor, radius: s.borderRadius, width: s.width, hiddenNative: getComputedStyle(document.getElementById('pickerGrid')).scrollbarWidth }; });
      assert.deepEqual(scrollbarStyles, { color: 'rgb(152, 162, 174)', radius: '999px', width: '10px', hiddenNative: 'none' });
      await page.mouse.click(trackBounds.x + 5, trackBounds.y + trackBounds.height - 8);
      assert.ok(await page.locator('#pickerGrid').evaluate(element => element.scrollTop > 0), 'Clicking the track scrolls the cards');
      const thumbBounds = await page.locator('.picker-scrollbar-thumb').boundingBox();
      await page.mouse.move(thumbBounds.x + 5, thumbBounds.y + thumbBounds.height / 2);
      await page.mouse.down(); await page.mouse.move(thumbBounds.x + 5, trackBounds.y, { steps: 8 }); await page.mouse.up();
      assert.equal(await page.locator('#pickerGrid').evaluate(element => element.scrollTop), 0, 'Dragging the thumb to the top scrolls to the top');
      await page.mouse.move(trackBounds.x + 5, trackBounds.y + trackBounds.height / 2); await page.mouse.wheel(0, 180);
      await page.waitForFunction(() => document.getElementById('pickerGrid').scrollTop > 0);
      const scrolled = await page.locator('#pickerGrid').evaluate(element => { element.scrollTop = 100; return { scrollTop: element.scrollTop, overflow: element.scrollHeight > element.clientHeight }; });
      assert.equal(scrolled.overflow, true); assert.ok(scrolled.scrollTop > 0);
      assert.deepEqual(await page.locator('#assetPicker header').boundingBox(), headerBounds, 'Only cards scroll; the header stays fixed');
      const overlap = await page.evaluate(() => {
        const header = document.querySelector('#assetPicker header'), h = header.getBoundingClientRect(), card = document.querySelector('.picker-card'), c = card.getBoundingClientRect();
        const x = c.left + c.width / 2, y = h.bottom - 10;
        return { underHeader: c.top < h.bottom && c.bottom > h.top, headerOnTop: header.contains(document.elementFromPoint(x, y)), blur: getComputedStyle(header).backdropFilter };
      });
      assert.equal(overlap.underHeader, true, 'Cards scroll underneath the translucent header');
      assert.equal(overlap.headerOnTop, true, 'Header controls stay above the cards');
      assert.match(overlap.blur, /blur/);
      if (width === 1440) await page.locator('#assetPicker').screenshot({ path: path.join(__dirname, 'design-picker-glass-header.png') });
      await card('extra-3').click(); await card('extra-4').click();
      assert.equal(await page.locator('.picker-selected').count(), 2);
      assert.deepEqual(await page.evaluate(() => window.addedAssets), [], 'Selecting cards does not add them');
      if (width !== 760) await page.locator('#assetPicker').screenshot({ path: path.join(__dirname, width === 1440 ? 'design-picker-multiselect.png' : 'design-picker-multiselect-mobile.png') });
      await card('extra-3').click(); await card('extra-4').click();
      await page.locator('#pickerBack').click(); await page.locator('#pickerBack').click();
      await page.waitForFunction(() => document.querySelector('.picker-scrollbar-thumb').offsetHeight === document.getElementById('pickerScrollbar').clientHeight);
      await page.waitForFunction(() => getComputedStyle(document.getElementById('confirmAssetPicker')).width === '34px');
      const styles = await page.evaluate(() => {
        const buttons = ['pickerBack', 'closeAssetPicker', 'confirmAssetPicker'].map(id => { const element = document.getElementById(id), s = getComputedStyle(element), icon = element.querySelector('.picker-confirm-icon') || element; return { width: s.width, height: s.height, radius: s.borderRadius, icon: getComputedStyle(icon, '::before').content, stroke: getComputedStyle(icon, '::before').height, secondStroke: getComputedStyle(icon, '::after').height }; });
        const title = getComputedStyle(document.querySelector('.picker-card-name'));
        return { buttons, fontSize: title.fontSize, fontWeight: title.fontWeight };
      });
      assert.equal(styles.fontSize, '14px'); assert.equal(styles.fontWeight, '550');
      styles.buttons.forEach((button, index) => { assert.equal(button.width, button.height); assert.equal(button.radius, index === 2 ? '999px' : '50%'); assert.equal(button.icon, '""'); });
      assert.equal(styles.buttons[0].stroke, styles.buttons[1].stroke);
      styles.buttons.forEach(button => { assert.equal(button.stroke, '2px'); assert.equal(button.secondStroke, '2px'); });
      const categoryButton = page.locator('#pickerCategory'), categoryMenu = page.locator('#pickerCategoryMenu');
      const chooseCategory = async value => { await categoryButton.click(); await page.locator(`[data-picker-category="${value}"]`).click(); };
      assert.equal(await page.locator('#pickerCategoryLabel').textContent(), '全部');
      assert.equal(await categoryButton.evaluate(button => getComputedStyle(button).fontSize), width === 1440 ? '16px' : '14px');
      await categoryButton.click();
      assert.equal(await categoryMenu.isVisible(), true);
      assert.deepEqual(await categoryMenu.locator('button').allTextContents(), ['全部', '面布', '边布', '包边条', '其他']);
      await categoryMenu.evaluate(menu => Promise.all(menu.getAnimations().map(animation => animation.finished)));
      await categoryButton.evaluate(button => Promise.all(button.getAnimations({ subtree: true }).map(animation => animation.finished.catch(() => {}))));
      if (width !== 760) await page.locator('#assetPicker').screenshot({ path: path.join(__dirname, width === 1440 ? 'design-picker-category-dropdown.png' : 'design-picker-category-dropdown-mobile.png') });
      await page.keyboard.press('Escape');
      assert.equal(await categoryMenu.isVisible(), false, 'Escape closes the dropdown');
      assert.equal(await page.locator('#assetPicker').isVisible(), true, 'Escape keeps the material window open');
      await categoryButton.click(); await page.locator('#pickerSearch').click();
      assert.equal(await categoryMenu.isVisible(), false, 'Clicking outside closes the dropdown');
      await chooseCategory('面布');
      assert.equal(await card('root-material').count(), 0);
      assert.equal(await card('outer').count(), 1, 'Category filters keep folders navigable');
      await card('outer').click(); await card('inner').click();
      assert.equal(await page.locator('.picker-card').count(), 9, 'Fabric category persists across folders');
      await card('nested').click();
      await chooseCategory('边布');
      assert.equal(await page.locator('.picker-card').count(), 8);
      assert.equal(await page.locator('.picker-confirm-count').textContent(), '1', 'Category filtering keeps hidden selections');
      await categoryButton.click(); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter');
      assert.equal(await page.locator('#pickerCategoryLabel').textContent(), '包边条');
      assert.equal(await page.locator('.picker-card').count(), 7, 'Keyboard selection filters binding materials');
      const headerControlsFit = await page.evaluate(() => {
        const category = document.getElementById('pickerCategory').getBoundingClientRect(), search = document.querySelector('.picker-search').getBoundingClientRect(), close = document.getElementById('closeAssetPicker').getBoundingClientRect();
        return category.right < search.left && search.right <= close.left;
      });
      assert.equal(headerControlsFit, true, 'The longer category label fits beside search and Close');
      await chooseCategory('其他');
      assert.equal(await page.locator('.picker-card').count(), 7);
      await page.locator('#pickerBack').click(); await page.locator('#pickerBack').click();
      assert.equal(await card('root-material').count(), 1, 'Uncategorized materials appear under Other');
      await chooseCategory('all');
      await card('outer').click(); await card('inner').click();
      assert.equal(await page.locator('.picker-card').count(), 31, 'All restores every material');
      assert.equal(await card('nested').getAttribute('aria-pressed'), 'true');
      await card('nested').click();
      await page.locator('#pickerBack').click(); await page.locator('#pickerBack').click();
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#assetPicker').screenshot({ path: path.join(__dirname, 'design-picker-navigation.png') });
    await page.locator('#pickerSearch').fill('不存在');
    await page.locator('#assetPicker').screenshot({ path: path.join(__dirname, 'design-picker-empty.png') });
    await page.locator('#pickerSearch').fill('');
    await card('root-material').click();
    assert.equal(await card('root-material').getAttribute('aria-pressed'), 'true');
    await card('root-material').click();
    assert.equal(await card('root-material').getAttribute('aria-pressed'), 'false');
    assert.equal(await page.locator('#confirmAssetPicker').isDisabled(), true);
    await card('root-material').click();
    await card('outer').click(); await card('inner').click(); await card('nested').click();
    await page.locator('#pickerSearch').fill('面料 0'); await card('extra-0').click();
    await page.locator('#pickerSearch').fill('不存在');
    assert.equal(await page.locator('.picker-card').count(), 0);
    await page.waitForFunction(() => document.getElementById('assetPicker').getAttribute('aria-busy') === 'false');
    assert.equal(await page.locator('#confirmAssetPicker').isEnabled(), true, 'Hidden selections remain available for confirmation');
    await page.locator('#pickerSearch').fill('');
    assert.equal(await card('nested').getAttribute('aria-pressed'), 'true');
    assert.equal(await card('extra-0').getAttribute('aria-pressed'), 'true');
    await page.locator('#pickerBack').click(); await page.locator('#pickerBack').click();
    assert.equal(await card('root-material').getAttribute('aria-pressed'), 'true', 'Selection survives folder navigation');
    assert.deepEqual(await page.evaluate(() => window.addedAssets), []);
    await page.locator('#confirmAssetPicker').click();
    await page.waitForFunction(() => !document.getElementById('assetPicker').open);
    assert.deepEqual(await page.evaluate(() => window.addedAssets), ['root-material', 'nested', 'extra-0']);
    assert.equal(await page.locator('#assetPicker').isVisible(), false);
    await open(); assert.equal(await page.locator('#pickerBack').isDisabled(), true);
    assert.equal(await page.locator('#confirmAssetPicker').isDisabled(), true);
    await card('root-material').click();
    await page.locator('#closeAssetPicker').click(); assert.equal(await page.locator('#assetPicker').isVisible(), false);
    await open(); assert.equal(await page.locator('#confirmAssetPicker').isDisabled(), true);
    await card('root-material').click(); await page.keyboard.press('Escape');
    await open(); assert.equal(await page.locator('#confirmAssetPicker').isDisabled(), true);
    assert.deepEqual(await page.evaluate(() => window.addedAssets), ['root-material', 'nested', 'extra-0'], 'Close and Escape discard unconfirmed choices');
    await card('root-material').click(); await card('outer').click(); await card('inner').click(); await card('nested').click();
    await page.evaluate(() => { window.pausePickerAdd = true; window.failPickerAsset = 'nested'; });
    await page.locator('#confirmAssetPicker').click();
    await page.waitForFunction(() => !!window.resumePickerAdd);
    assert.equal(await page.locator('#confirmAssetPicker').isDisabled(), true);
    assert.equal(await page.locator('#closeAssetPicker').isDisabled(), true);
    assert.equal(await page.locator('#pickerSearch').isDisabled(), true);
    assert.equal(await page.locator('#pickerCategory').isDisabled(), true);
    assert.equal(await page.locator('#pickerBack').isDisabled(), true);
    assert.equal(await card('nested').isDisabled(), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#assetPicker').isVisible(), true, 'Pending additions cannot be dismissed');
    await page.evaluate(() => { document.getElementById('confirmAssetPicker').onclick(); window.pausePickerAdd = false; window.resumePickerAdd(); });
    await page.waitForFunction(() => document.getElementById('assetPicker').getAttribute('aria-busy') === 'false');
    assert.equal(await page.locator('#assetPicker').isVisible(), true, 'A failed batch keeps remaining choices open');
    assert.equal(await card('nested').getAttribute('aria-pressed'), 'true');
    assert.deepEqual(await page.evaluate(() => window.addAttempts), ['root-material', 'nested', 'extra-0', 'root-material', 'nested'], 'Confirm cannot start a duplicate batch while busy');
    assert.deepEqual(await page.evaluate(() => window.addedAssets), ['root-material', 'nested', 'extra-0', 'root-material']);
    assert.match(await page.evaluate(() => window.pickerNotifications[0]), /添加失败/);
    await page.evaluate(() => { window.failPickerAsset = null; });
    await page.locator('#confirmAssetPicker').click();
    await page.waitForFunction(() => !document.getElementById('assetPicker').open);
    assert.deepEqual(await page.evaluate(() => window.addedAssets), ['root-material', 'nested', 'extra-0', 'root-material', 'nested'], 'Retry adds only the remaining selections');
    await page.evaluate(() => window.pickerWorkspace.setType('pattern')); await open();
    assert.equal(await card('outer').count(), 0);
    await card('patterns').click(); await card('pattern').click();
    assert.equal(await page.locator('#assetPicker').isVisible(), true);
    await page.locator('#confirmAssetPicker').click();
    await page.waitForFunction(() => !document.getElementById('assetPicker').open);
    assert.equal(await page.evaluate(() => window.addedAssets.at(-1)), 'pattern');
    assert.deepEqual(errors, []);
    console.log('PASS: category dropdown, five filters, keyboard navigation, dismissal, larger font and responsive header; multi-selection, explicit confirmation, failure retry, scrollbar and glass header.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
