const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/5/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const base = process.env.FORM_BASE_URL || 'http://127.0.0.1:4173';
const storageKey = 'spenic.developer-settings.v1';
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(base);
    const ready = () => page.waitForFunction(() => document.getElementById('loading').hidden && !document.getElementById('dayCycle').disabled, null, { timeout: 60000 });
    await ready();
    const toggle = page.locator('#developerToggle'), panel = page.locator('#developerPanel');
    const unlock = async () => { await page.locator('.brand-logo').hover(); await page.keyboard.type('admin'); };
    const saved = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), storageKey);
    assert.equal(await toggle.isVisible(), false);
    await page.keyboard.type('admin'); assert.equal(await toggle.isVisible(), false, 'Typing away from the logo does not reveal entry');
    await unlock(); assert.equal(await toggle.isVisible(), true);
    await toggle.click(); assert.equal(await panel.isVisible(), true);
    await page.waitForFunction(() => document.getElementById('developerCpu').textContent.includes('ms'));
    assert.match(await page.locator('#developerGpu').textContent(), /ms|不支持|等待采样/);
    await page.screenshot({ path: 'checks/developer-desktop.png' });
    const logoBounds = await page.locator('.brand').boundingBox(), toggleBounds = await toggle.boundingBox();
    assert.ok(toggleBounds.x >= logoBounds.x + logoBounds.width, 'Developer entry follows brand');
    for (const [phase, exposure] of [['morning', '0.8'], ['evening', '0.9'], ['night', '1']]) {
      await page.locator('#developerPhase').selectOption(phase); await page.locator('#developerLoadPhase').click();
      await page.locator('[data-dev-scene="exposure"]').fill(exposure);
      await page.locator('#developerSavePhase').click();
      assert.equal((await saved()).presets[phase].scene.exposure, Number(exposure));
    }
    await page.locator('#developerTransition').fill('0.6'); await page.locator('#developerHold').fill('0.3');
    await page.locator('#developerTimingForm button').click();
    assert.deepEqual((await saved()).timing, { transition: 600, hold: 300 });
    const beforeInvalid = await saved();
    await page.locator('#developerFile').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"version":9}') });
    await page.waitForFunction(() => document.getElementById('toast').textContent.startsWith('导入失败'));
    assert.deepEqual(await saved(), beforeInvalid);
    const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#developerExport').click()]);
    const exported = JSON.parse(await fs.readFile(await download.path(), 'utf8'));
    assert.deepEqual(exported, beforeInvalid, 'Export includes saved presets and showroom timing');
    await page.reload(); await ready();
    assert.equal(await toggle.isVisible(), false, 'Unlock does not persist across reload');
    assert.equal(await page.locator('#exposure').inputValue(), '0.8', 'Saved morning automatically loads');
    await unlock(); await toggle.click();
    assert.equal(await page.locator('#developerTransition').inputValue(), '0.6');
    assert.equal(await page.locator('#developerHold').inputValue(), '0.3');
    await page.locator('#developerHold').focus(); await page.locator('.brand-logo').hover(); await page.keyboard.type('admin');
    assert.equal(await toggle.isVisible(), true, 'Typing in a field never hides the entry');
    const imported = structuredClone(exported); imported.timing.hold = 400;
    await page.locator('#developerFile').setInputFiles({ name: 'settings.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(imported)) });
    await page.waitForFunction(() => document.getElementById('developerHold').value === '0.4');
    assert.deepEqual(await saved(), imported, 'Valid import persists complete configuration');
    await page.locator('#showroomMode').click();
    await page.waitForFunction(() => document.body.classList.contains('showroom-mode'));
    assert.equal(await panel.isVisible(), true, 'Developer monitoring remains visible in showroom');
    await page.waitForFunction(() => document.getElementById('developerSceneControls').disabled);
    await page.waitForFunction(() => document.getElementById('dayCycle').dataset.phase === 'night', null, { timeout: 10000 });
    await page.keyboard.press('Escape');
    await page.waitForFunction(() => !document.body.classList.contains('showroom-mode'));
    assert.equal(await page.locator('#exposure').inputValue(), '0.8', 'Exiting showroom restores scene');
    await unlock(); assert.equal(await toggle.isVisible(), false); assert.equal(await panel.isVisible(), false);
    await unlock(); await toggle.click();
    await page.setViewportSize({ width: 390, height: 844 });
    const bounds = await panel.boundingBox(), entry = await toggle.boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390 && bounds.y + bounds.height <= 844);
    assert.ok(entry.x >= 0 && entry.x + entry.width <= 390);
    await page.locator('#developerClose').scrollIntoViewIfNeeded();
    await page.screenshot({ path: 'checks/developer-mobile.png' });
    await page.locator('#developerClose').click(); assert.equal(await panel.isVisible(), false);
    assert.deepEqual(errors, []);
    console.log('PASS: hover secret, form exclusion, live metrics, three phase saves, refresh persistence, timing, export, invalid import, showroom, hide and mobile layout');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
