import assert from 'node:assert/strict';
import {Group, Mesh, BoxGeometry, MeshStandardMaterial, Texture} from '../vendor/three/build/three.module.js';
import {assignMaterial, slotMaterial, rebuildMaterialUsage, serializeAssignments, restoreAssignments} from '../material-assignments.js';
const a=new MeshStandardMaterial({color:0x2244ff}), b=new MeshStandardMaterial({color:0xffffff});
a.map=new Texture();a.roughness=.23;
const entries=[a,b].map((material,id)=>({id,material,meshes:new Set()}));
const sharedSlots=[a,b], multi=new Mesh(new BoxGeometry(),sharedSlots), other=new Mesh(new BoxGeometry(),sharedSlots), single=new Mesh(new BoxGeometry(),b);
const model=new Group();model.add(multi,other,single);
const original=serializeAssignments(model,entries);
assert.deepEqual(original,[[0,1],[0,1],[1]]);
assert.equal(assignMaterial(multi,1,a),true);
assert.equal(slotMaterial(multi,1),a);
assert.equal(slotMaterial(other,1),b,'Shared material arrays on other meshes must not change');
assert.equal(slotMaterial(multi,0),a,'Unrelated slots must not change');
assert.equal(slotMaterial(multi,1).map,a.map,'The assigned material includes PBR textures');
rebuildMaterialUsage(model,entries);
assert.equal(entries[0].meshes.size,2);assert.equal(entries[1].meshes.size,2);
assert.equal(assignMaterial(single,0,a),true);
assert.equal(assignMaterial(single,2,b),false);
assert.equal(assignMaterial(multi,-1,b),false);
assert.equal(assignMaterial(multi,99,b),false);
const saved=JSON.parse(JSON.stringify(serializeAssignments(model,entries)));
restoreAssignments(model,entries,original);
assert.deepEqual(serializeAssignments(model,entries),original);
restoreAssignments(model,entries,saved);
assert.deepEqual(serializeAssignments(model,entries),[[0,0],[0,1],[0]]);
assert.equal(entries[0].meshes.size,3);assert.equal(entries[1].meshes.size,1);
assert.throws(()=>restoreAssignments(model,entries,[[1,1],[1,999],[1]]));
assert.deepEqual(serializeAssignments(model,entries),saved,'Invalid project assignments must not partially apply');
restoreAssignments(model,entries,undefined);
assert.deepEqual(serializeAssignments(model,entries),saved,'Legacy projects remain supported');
console.log('PASS: slot replacement, shared-array isolation, PBR retention, usage, undo/restore, invalid and legacy projects');
